export const mockOrderData: {
  id?: number;
  btcLiquidityOneId: string;
  btcLiquidityOneIdLabel: string;
  rateOneId: string;
  rateOneIdLabel: string;
  totalOneId: string;
  totalOneIdLabel: string;
}[] = [
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
  {
    btcLiquidityOneId: '02',
    btcLiquidityOneIdLabel: 'BTC',
    rateOneId: '10',
    rateOneIdLabel: 'EMME',
    totalOneId: '20',
    totalOneIdLabel: 'EMME',
  },
];

export const mockLiquidityMarketsData: {
  id: number;
  pairId: string;
  priceId: number;
  volumeId: number;
}[] = [
  { id: 1, pairId: 'BTC/USD', priceId: 0.01052, volumeId: 4189 },
  { id: 2, pairId: 'VBK/USD', priceId: 0.000001, volumeId: 16 },
  { id: 3, pairId: 'NEO/USD', priceId: 0.01057, volumeId: 199 },
  { id: 4, pairId: 'LINK/USD', priceId: 0.00007, volumeId: 1371 },
  { id: 5, pairId: 'BTC/USD', priceId: 36779, volumeId: 2477216 },
];

export const mockClosedOrdersData: {
  id?: number;
  placed: string;
  market: string;
  type: string;
  typeColor: 'success' | 'warn';
  price: number;
  priceLabel: string;
  quantity: number;
  quantityLabel: string;
  total: number;
  totalLabel: string;
  value: number;
  valueLabel: string;
}[] = [
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:01:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:02:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Ask',
    typeColor: 'warn',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Ask',
    typeColor: 'warn',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Ask',
    typeColor: 'warn',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Ask',
    typeColor: 'warn',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Ask',
    typeColor: 'warn',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Ask',
    typeColor: 'warn',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Ask',
    typeColor: 'warn',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
  {
    placed: '2021-09-15 10:00:00',
    market: 'BTX/BTC/VBK',
    type: 'Liquidity Bid',
    typeColor: 'success',
    price: 0.0002,
    priceLabel: 'BTC',
    quantity: 10,
    quantityLabel: 'VBK',
    total: 0.0012,
    totalLabel: 'BTC',
    value: 72.63,
    valueLabel: 'usd',
  },
];
